spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postierhr
    username: postierhr
    password: postierhr
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
    
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB
    
app:
  upload:
    dir: uploads
    
server:
  servlet:
    session:
      cookie:
        secure: false
        
logging:
  level:
    root: INFO
    com.example.postierhr: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE